# Generated by Django 2.2.1 on 2019-08-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainishadiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
