# Generated by Django 2.2.1 on 2019-08-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainishadiApp', '0002_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], default='', max_length=10),
        ),
    ]
