# Generated by Django 2.2.1 on 2019-08-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sainishadiApp', '0003_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='published',
        ),
    ]
